### ISSUE TITLE
Prod checklist 

### ISSUE THREAD

**Issue by jackmellis** [stop-n-swop/sharkfood-island#127]
- [x] Social media
- [x] Set up prod paypal account
- [x] Switch google oauth to production
- [x] Set up prod paypal oauth
- [x] Set up prod facebook oauth
- [x] Update env vars
- [x] K8s
- [x] Deploy from master
- [x] Deploy and set up staging
- [x] Populate prod database
- [x] Make sure analytics is set up for prod
- [x] Make sure commitlint and precommit hooks are active
- [x] Add some github actions to PRs
- [x] Ensure build pipeline is doing lint/testing/etc.
- [x] Transfer domain from 123 to name
- [x] Clean up / segregate prote/staging images on DO Spaces
- [x] get latest rawg dataset
- [x] set up prod database
- [x] rebase
