### ISSUE TITLE
Purchase with balance credit

### ISSUE THREAD

**Issue by jackmellis** [stop-n-swop/sharkfood-island#139]
- [x] Show credit at checkout
  - [x] Show available balance at checkout
  - [x] Option to use balance for payment
  - [x]  User is given some sort of special discount on their balance amount (like an extra 2%)
  - [x] Adjust the order accordingly - probably have an additional field for balance used
  - [x] Make sure the user doesn't create 2 orders at the same time and use their balance twice or something
- [x] Use Credit for payments
  - [x] Only have paypal debit the remaining amount
  - [x] If they have more than enough balance for the entire payment, skip paypal entirely
  - [x] the seller should still receive the same amount of money
- [x] Ledger changes
  - [x] we should be factoring in the amount of credited funds might not be the entire listing amount
  - [x] we still want to charge the platform fee of the entire amount, but the protection fee will only cover the amount credited
  - [x] refunds should only refund the debited amount, but it should also undo the balance
