### ISSUE TITLE
Storefront

### ISSUE THREAD

**Issue by jackmellis** [stop-n-swop/sharkfood-island#94]
- [x] https://github.com/stop-n-swop/sharkfood-island/issues/189
- [x] https://github.com/stop-n-swop/sharkfood-island/issues/190
- [x] https://github.com/stop-n-swop/sharkfood-island/issues/192
- [x] https://github.com/stop-n-swop/sharkfood-island/issues/191
- [x] https://github.com/stop-n-swop/sharkfood-island/issues/193
- [x] https://github.com/stop-n-swop/sharkfood-island/issues/188
